apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
rules:
  - apiGroups: ["openstack.krateo.io"]
    resources: ["*"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  
  - apiGroups: ["openstack.krateo.io"]
    resources:
      - computeinstances/status
      - projects/status
      - users/status
      - quota/status
    verbs: ["get", "patch", "update"]
  
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]